# Generated by Django 5.0.4 on 2024-04-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dermatologist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='patients',
            name='registered_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
