# Generated by Django 5.0.4 on 2024-04-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dermatologist', '0002_alter_patients_options_patients_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
